version: '2.3'

services:
  backend:
    image: nginx:latest
    container_name: otot-a1-backend
    depends_on:
      - frontend
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  frontend:
    image: frontend
    container_name: otot-a1-frontend
    build:
      context: ./frontend
    ports:
      - 3001:80
    restart: on-failure
